### ISSUE TITLE
Add more transition detection options

### ISSUE THREAD

**Issue by SimeonC** [SimeonC/jira-gitlab-seneschal#30]
Need to add more configuration options to allow us to trigger transitions on the following;
* ~~Any ticket mention~~
* Mention in the MR description
* ~~Ticket in Branch name. This needs options for the two scenarios; `XXX-123/...` and `.../XXX-123` (same as `XXX-123` and `XXX-123-short-desc`)~~
* Ensure punctuation is ignored around the ticket numbers

Ended up removing 2 of these requirements because they would be an all or nothing at best. If you wanted to turn on/off at a project level you'd need to keep track of a gitlab project <-> jira project link and that would get extremely difficult to maintain.

**Comment by jaygeeseman** [comment]
I question the necessity of linking by ticket number in branch name. If it's easy, I guess it doesn't hurt to have it though. The other two seem pretty fundamental to what we want to do.
